name: '🐛 Bug report'
description: Report a reproducible bug or regression
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        This issue tracker is for reporting reproducible bugs or regression's found in [tailwindcss-themer](https://github.com/RyanClementsHax/tailwindcss-themer)
        If you have a question about how to achieve something and are struggling, please post a question
        inside of tailwindcss-themer's [Discussions tab](https://github.com/RyanClementsHax/tailwindcss-themer/discussions)

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - tailwindcss-themer's [Discussions tab](https://github.com/RyanClementsHax/tailwindcss-themer/discussions)
         - tailwindcss-themer's [Open Issues](https://github.com/RyanClementsHax/tailwindcss-themer/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
         - tailwindcss-themer's [Closed Issues](https://github.com/RyanClementsHax/tailwindcss-themer/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)

        The more information you fill in, the better the community can help you.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Your minimal, reproducible example
      description: |
        Please add a link to a minimal reproduction. You can use this codesandbox template https://codesandbox.io/p/devbox/tailwindcss-themer-example-react-vite-typescript-hx2j7f if you would like.
        Note:
        - Your bug may get fixed much faster if we can run your code and it doesn't have dependencies other than a base framework and tailwindcss-themer
        - To create your own shareable code example, you can use CodeSandbox (https://codesandbox.io/s/new) or Stackblitz (https://stackblitz.com/).
        - Please make sure the example is complete and runnable
        - Please read these tips for providing a minimal example: https://stackoverflow.com/help/mcve.
      placeholder: |
        e.g. Code Sandbox, Stackblitz, or repo link
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: |
        Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: |
        Please let us know which Operting System, Browser and Browser version you were using when the issue occurred.
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux, iOS, Android]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 91.1]
    validations:
      required: true
  - type: input
    id: rq-version
    attributes:
      label: tailwindcss-themer version
      description: |
        Please let us know the exact version of tailwindcss-themer you were using when the issue occurred. Please don't just put in "latest", as this is subject to change.
      placeholder: |
        e.g. v1.3.1
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
